import type { Facility } from "../domain/facility.ts";

export const MOCK_FACILITIES: readonly Facility[] = [
  {
    slug: "kohoku-family-consultation",
    name: "港北こども・家族相談室",
    operator: "よこはま支援さがし デモ運営局",
    operatingDepartment: "港北エリア相談チーム",
    summary:
      "子育てや家庭のこと、学校に行きづらい気持ちを、専門の相談員と一緒に整理できる相談窓口です。",
    ward: "kohoku",
    supportThemes: ["school-absence", "family", "low-mood"],
    targetAudiences: ["child", "guardian", "school"],
    whatYouCanConsult:
      "学校に行けない・行きづらいこと、家庭での過ごし方、子育ての悩みなどを相談できます。",
    whoCanUse: "横浜市内にお住まいの子どもとその保護者、学校関係者",
    eligibility: "年齢や在籍校を問わず相談できます。",
    howToUse:
      "電話または窓口で相談予約をしてください。空きがある場合は当日の相談もできます。",
    consultationMethods: ["phone", "inperson"],
    cost: "free",
    reservationRequired: false,
    anonymousConsultation: false,
    guardianOnlyConsultation: true,
    receptionHours: "平日 9:00〜17:00（表示用モック）",
    officialUrl: "https://example.com/kohoku-family-consultation",
    imageVariant: "conversation",
    sourceName: "表示用モックデータ",
    sourceUrl: "https://example.com/mock-source",
    lastCheckedAt: "2026-07-01",
    verificationStatus: "official-verified",
  },
  {
    slug: "hiyori-community-space",
    name: "つながる居場所 ひより",
    operator: "NPO法人 ひより（表示用モック）",
    operatingDepartment: null,
    summary:
      "学校以外で安心して過ごしたい子どもと、見守る家族のための小さな地域の居場所です。",
    ward: "kohoku",
    supportThemes: ["school-absence", "low-mood", "bullying"],
    targetAudiences: ["child", "guardian", "supporter"],
    whatYouCanConsult:
      "日中の居場所、友人関係、学び直し、家から出ることへの不安について相談できます。",
    whoCanUse: "小学生から高校生年代の子どもとその家族",
    eligibility: "見学後に利用方法を一緒に決めます。",
    howToUse: "メールまたはオンラインで見学を申し込んでください。",
    consultationMethods: ["inperson", "online", "email"],
    cost: "partial",
    reservationRequired: true,
    anonymousConsultation: null,
    guardianOnlyConsultation: true,
    receptionHours: "火〜土 10:00〜16:00（表示用モック）",
    officialUrl: "https://example.com/hiyori-community-space",
    imageVariant: "community",
    sourceName: "表示用モックデータ",
    sourceUrl: null,
    lastCheckedAt: "2026-07-01",
    verificationStatus: "operator-verified",
  },
  {
    slug: "kohoku-learning-support",
    name: "まなびサポート港北",
    operator: "一般社団法人 みらい学習室（表示用モック）",
    operatingDepartment: "相談・学習支援部",
    summary:
      "自分のペースで学びたい子どもに、学習相談と少人数の活動プログラムを提供します。",
    ward: "kohoku",
    supportThemes: ["school-absence", "low-mood"],
    targetAudiences: ["child", "guardian", "school", "supporter"],
    whatYouCanConsult: "学習の遅れ、進路、学校との付き合い方を相談できます。",
    whoCanUse: "小学生・中学生・高校生年代の子ども",
    eligibility: null,
    howToUse: "初回面談のあと、希望する活動日を選びます。",
    consultationMethods: ["inperson", "online"],
    cost: "free",
    reservationRequired: true,
    anonymousConsultation: false,
    guardianOnlyConsultation: true,
    receptionHours: null,
    officialUrl: null,
    imageVariant: "learning",
    sourceName: "表示用モックデータ",
    sourceUrl: null,
    lastCheckedAt: "2026-06-15",
    verificationStatus: "unverified",
  },
  {
    slug: "tsuzuki-parent-support",
    name: "つづき親子サポート",
    operator: "つづき地域サポートネット（表示用モック）",
    operatingDepartment: "家族相談窓口",
    summary:
      "保護者がひとりで抱え込まないために、家庭での関わり方や利用できる制度を一緒に考えます。",
    ward: "tsuzuki",
    supportThemes: ["school-absence", "family", "caregiving"],
    targetAudiences: ["guardian", "supporter"],
    whatYouCanConsult: "親子関係、きょうだいへの影響、家族のケアを相談できます。",
    whoCanUse: "子どものことで悩む保護者・家族",
    eligibility: "保護者のみでも利用できます。",
    howToUse: "電話で相談日時を予約してください。",
    consultationMethods: ["phone", "inperson"],
    cost: "free",
    reservationRequired: true,
    anonymousConsultation: true,
    guardianOnlyConsultation: true,
    receptionHours: "平日 10:00〜18:00（表示用モック）",
    officialUrl: "https://example.com/tsuzuki-parent-support",
    imageVariant: "conversation",
    sourceName: "表示用モックデータ",
    sourceUrl: null,
    lastCheckedAt: "2026-06-20",
    verificationStatus: "official-verified",
  },
  {
    slug: "tsurumi-online-room",
    name: "つるみオンライン相談室",
    operator: "子どもユース相談ネット（表示用モック）",
    operatingDepartment: null,
    summary:
      "外出が難しいときも、チャットやオンラインで気持ちを話せる子ども向け相談室です。",
    ward: "tsurumi",
    supportThemes: ["school-absence", "low-mood", "bullying"],
    targetAudiences: ["child", "guardian"],
    whatYouCanConsult: "学校、友人、家族、自分の気持ちについて相談できます。",
    whoCanUse: "18歳未満の子どもとその保護者",
    eligibility: "ニックネームで相談できます。",
    howToUse: "受付時間内にチャットを開始するか、オンライン面談を予約します。",
    consultationMethods: ["online", "chat"],
    cost: "free",
    reservationRequired: false,
    anonymousConsultation: true,
    guardianOnlyConsultation: true,
    receptionHours: "毎日 15:00〜21:00（表示用モック）",
    officialUrl: "https://example.com/tsurumi-online-room",
    imageVariant: "community",
    sourceName: "表示用モックデータ",
    sourceUrl: "https://example.com/mock-source",
    lastCheckedAt: "2026-07-10",
    verificationStatus: "operator-verified",
  },
  {
    slug: "aoba-learning-place",
    name: "あおば学びの居場所",
    operator: "青葉ユースセンター（表示用モック）",
    operatingDepartment: "居場所支援チーム",
    summary:
      "学習や創作活動を通して、自分に合う過ごし方をゆっくり見つけられる居場所です。",
    ward: "aoba",
    supportThemes: ["school-absence", "bullying"],
    targetAudiences: ["child", "guardian", "school"],
    whatYouCanConsult: "学習、進路、友人関係について相談できます。",
    whoCanUse: "横浜市内の中学生・高校生年代",
    eligibility: "事前見学が必要です。",
    howToUse: "公式サイトのフォームから見学を申し込みます。",
    consultationMethods: ["inperson", "email"],
    cost: "paid",
    reservationRequired: true,
    anonymousConsultation: false,
    guardianOnlyConsultation: true,
    receptionHours: "水〜土 11:00〜17:00（表示用モック）",
    officialUrl: "https://example.com/aoba-learning-place",
    imageVariant: "learning",
    sourceName: "表示用モックデータ",
    sourceUrl: null,
    lastCheckedAt: "2026-05-30",
    verificationStatus: "unverified",
  },
];
